Repository elastic/stream, pull requests merged in 2022-09, with the labels that each got.

#40 Update to Go 1.19.1 and update deps
  .ci/Jenkinsfile
  .github/workflows/golangci-lint.yml
  .go-version
  CHANGELOG.md
  Dockerfile
  go.mod
  go.sum
Labels: Team:Security-External Integrations

#41 Add Lumberjack output
  CHANGELOG.md
  README.md
  command/root.go
  go.mod
  go.sum
  pkg/output/lumberjack/lumberjack.go
  pkg/output/lumberjack/lumberjack_test.go
  pkg/output/options.go
Labels: enhancement, Team:Security-External Integrations

#42 bump golang version
  .ci/Jenkinsfile
  .ci/bump-go-release-version.sh
Labels: Team:Automation
